subscriptions:
    Binance:
        instruments: 
          - ETH/BTC
          - XRP/BTC

    Poloniex:
        instruments:
          - ETH/BTC
          - XRP/BTC

handlers:
    sql:
        connection: "sqlite:///.data/order_book.db"
